roottsApp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views 
from django.urls import path, include

from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', IndexView, name='index'),
    path('crud/', EncostaView, name='crud'),
    path('crud/search/', EncostaSearchView.as_view(), name='search_crud'),
    path('create/', CreateEncostaView, name='add_encosta'),
    path('update/<int:pk>/', UpdateEncostaView, name='upd_encosta'),
    path('delete/<int:pk>/', DeleteEncostaView, name='del_encosta'),
    path('encosta/<int:pk>/', EncostaSelecionadaView, name='view_encosta'),
    path('denuncia_formulario/',DenunciaFormView, name='DenunciaForm'),
    path('register/', register ,name='register'),
    path('user_register/', User_register.as_view() ,name='user_register'),
    path('engineer_register/', Engineer_register.as_view() ,name='engineer_register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('Engenheiro_formulario/',EngenheiroFormView, name='EngenheiroForm'),
    path('descricao/<int:pk>/',DescricaoView, name='view_descricao'),
    path('deleteForm/<int:pk>/',  DeleteformView, name='del_reporte'),
    path('risco/', RiscoView, name='risco'),
    path('risco/search/', RiscoSearchView.as_view(), name='search_risco'),
    path('encosta/pdf/<int:pk>', EncostaGeneratePDf, name='encosta_pdf'),
]
handler404 = "roottsApp.views.error_404_view"
handler404 = "roottsApp.views.error_401_view"

roottsProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('roottsApp.urls')),
]

admin.AdminSite.site_header = 'Banco de Encosta'
admin.AdminSite.site_title = 'Rotts'
admin.AdminSite.index_title = 'Sistema de Cadastro de Encostas'

roottsApp/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.
class Encosta(models.Model):
    nome = models.CharField(max_length=15)
    local = models.CharField(max_length=40)
    latitude = models.DecimalField(max_digits=20, decimal_places=10)
    longitude = models.DecimalField(max_digits=20, decimal_places=10)
    declividade = models.DecimalField(max_digits=20, decimal_places=10)
    numeroConstrucoes = models.DecimalField(max_digits=20, decimal_places=10)
    coeficienteUmidade = models.DecimalField(max_digits=20, decimal_places=10)
    proximidadeRedeViarias = models.DecimalField(max_digits=20, decimal_places=10)
    proximidadeCorposLiquidos = models.DecimalField(max_digits=20, decimal_places=10)

    PRIORITY_LEVELS = (
        ('Muito Baixo', 'Muito Baixo'),
        ('Baixo', 'Baixo'),
        ('Médio', 'Médio'),
        ('Alto', 'Alto'),
        ('Crítico', 'Crítico'),
    )
    prioridadeEncosta = models.CharField(max_length=30, choices=PRIORITY_LEVELS, default = 'Muito Baixo')

    def __str__(self):
        return self.nome, self.local

class Formulario_denuncia(models.Model):
    nome = models.CharField(max_length = 50)
    endereco = models.TextField(max_length = 100)
    data = models.DateField()
    titulo = models.CharField(max_length = 50)
    descricao = models.TextField(max_length=500)
    aprovado = models.BooleanField('aprovado', default=False)


    def __str__(self):
        return self.nome

class User(AbstractUser):
    is_engineer = models.BooleanField(default=False)

    def __str__(self):
        return self.username

class EngineerUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    nome = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    crea = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class RegularUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    nome = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)

    def __str__(self):
        return self.nome

roottsApp/views.py
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from django.db.models import Q
from django.views.generic import ListView

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import user_passes_test


from .forms import *
from .models import *

from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter



def EncostaGeneratePDf(request, pk):
  buf = io.BytesIO()
  c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
  textob = c.beginText()
  textob.setTextOrigin(inch, 2.5 * inch)
  textob.setFont("Helvetica", 14)
  encostas = Encosta.objects.get(id=pk)

  c.setFillColorRGB(0, 0, 0)
  c.setFont("Helvetica-Bold", 16)
  c.drawCentredString(300, 100, "Relatório de Risco de Deslizamento de Encosta")

  c.setFont("Helvetica", 14)
  c.drawCentredString(300, 125, "Dados do Relatório Encosta: " + encostas.nome)


  c.setFillColorRGB(0, 0.75, 0)
  c.setFont("Helvetica-Bold", 20)
  c.drawCentredString(100, 50, "Rootts")

  if encostas.prioridadeEncosta == 'Baixo':
    c.setFillColorRGB(0, 0.75, 0)
    c.drawCentredString(500, 50, "Baixa")
  elif encostas.prioridadeEncosta == 'Médio':
    c.setFillColorRGB(1, 0.75, 0)
    c.drawCentredString(500, 50, "Média")
  elif encostas.prioridadeEncosta == 'Alto':
    c.setFillColorRGB(1, 0, 0)
    c.drawCentredString(500, 50, "Alta")
  elif encostas.prioridadeEncosta == 'Crítico':
    c.setFillColorRGB(1, 0, 0)
    c.drawCentredString(500, 50, "Crítica")
  elif encostas.prioridadeEncosta == 'Muito Baixa':
    c.setFillColorRGB(0, 0, 0)
    c.drawCentredString(500, 50, "Muito Baixa")

  c.setFillColorRGB(0, 0, 0)


  lines = []

  lines.append("Endereço: " + str(encostas.local))
  lines.append("Latitude: " + str(encostas.latitude))
  lines.append("Longitude: " + str(encostas.longitude))
  lines.append("Declividade: " + str(encostas.declividade))
  lines.append("Coeficiente de Umidade: " + str(encostas.coeficienteUmidade))
  lines.append("Número de Construções por m²: " + str(encostas.numeroConstrucoes))
  lines.append("Proximidade de Redes Viarias por m²: " + str(encostas.proximidadeRedeViarias))
  lines.append("Proximidade de Corpos Liquidos por m²: " + str(encostas.proximidadeCorposLiquidos))

  for i in lines:
    textob.textLine(i)
  
  c.drawText(textob)
  c.showPage()
  c.save()
  buf.seek(0)

  return FileResponse(buf, as_attachment=True, filename='Encosta_' + str(encostas.id) + '.pdf')



def IndexView(request):
  return render(request, 'index.html')

@login_required(login_url='/login/')
@user_passes_test(lambda u: u.is_engineer, login_url='/login/')
def EncostaView(request):
  encostas = Encosta.objects.all()
  return render(request, 'crud.html', {'encostas': encostas})


class EncostaSearchView(ListView):
  model = Encosta
  template_name = 'crud.html'
  context_object_name = 'encostas'

  def get_queryset(self):
    query = self.request.GET.get('q')
    object_list = Encosta.objects.filter(
      Q(nome__icontains=query) | Q(local__icontains=query)
    )

    return object_list


@login_required(login_url='/login/')
@user_passes_test(lambda u: u.is_engineer, login_url='/login/')
def CreateEncostaView(request):
  form = EncostaForm(request.POST or None)
  if form.is_valid():
    form.save()
    return redirect('crud')
  return render(request, 'encosta_add.html', {'form': form})


@login_required(login_url='/login/')
@user_passes_test(lambda u: u.is_engineer, login_url='/login/')
def UpdateEncostaView(request, pk):
  encosta = Encosta.objects.get(id=pk)
  form = EncostaFormUpdate(request.POST or None, instance=encosta)
  if form.is_valid():
    form.save()
    return redirect('crud')
  return render(request, 'encosta_upd.html', {'form': form, 'encosta': encosta})


@login_required(login_url='/login/')
@user_passes_test(lambda u: u.is_engineer, login_url='/login/')
def DeleteEncostaView(request, pk):
  encosta = Encosta.objects.get(id=pk)
  if request.method == 'POST':
    encosta.delete()
    return redirect('crud')
  return render(request, 'encosta_del.html', {'encosta': encosta})


# Visualizar encosta selecionada
@login_required(login_url='/login/')
@user_passes_test(lambda u: u.is_engineer, login_url='/login/')
def EncostaSelecionadaView(request, pk):
  encosta = Encosta.objects.get(id=pk)
  return render(request, 'encosta_selecionada.html', {'encosta': encosta})



def DenunciaFormView(request):
  if request.method == 'GET':
    form = denunciaForm()
    return render(request,"denuncia_formulario.html",context ={'form': form})
  else:
    form = denunciaForm(request.POST)

    if form.is_valid():
      form.save()
      form = denunciaForm()
      messages.success(request, 'Seu relatório foi feito com sucesso')
      
      return render(request, 'denuncia_formulario.html', {'form': form})
    else:
      messages.error(request, 'Preencha o formulario corretamente')
      # messages.error(request, form.errors)
    return render(request,"denuncia_formulario.html",context ={'form': form})
  

# tratamento de erro

def error_404_view(request, exception):
  return render(request,'404.html', status = 404)

def error_401_view(request, exception):
  return render(request,'401.html', status = 401)

class User_register(CreateView):
  model = RegularUser
  form_class = RegularUserCreationForm
  template_name = "../templates/user_register.html"

  def get_context_data(self, **kwargs):
    kwargs['user_type'] = 'regular_user'
    return super().get_context_data(**kwargs)

  def form_valid(self, form):
    user = form.save()
    login(self.request, user)
    return redirect('index')


class Engineer_register(CreateView):
  model = EngineerUser
  form_class = EngineerUserCreationForm
  template_name = "../templates/engineer_register.html"

  def get_context_data(self, **kwargs):
    kwargs['user_type'] = 'engineer_user'
    return super().get_context_data(**kwargs)

  def form_valid(self, form):
    user = form.save()
    login(self.request, user)
    return redirect('index')


def register(request):
  return render(request, '../templates/register.html')



def login_view(request):
  username = request.POST['username']
  email = request.POST.get('email')
  password = request.POST.get('password')
  user = authenticate(request, username=username, email=email, password=password)
  if user is not None:
    if user.is_active:
      login(request, user)
      return redirect('index')
    else:
      return render(request, '../templates/login.html', {'error_message': 'Sua conta foi desativada'})
  else:
    return render(request, '../templates/login.html', {'error_message': 'Login invalido'})


@login_required
def logout_view(request):
  if request.user.is_authenticated:
    logout(request)
    return redirect('index')


def EngenheiroFormView(request):
  forms = Formulario_denuncia.objects.all()
  if request.method == "POST":
    # Get list of checked box id's
    id_list = request.POST.getlist('boxes')

    # Uncheck all events
    forms.update(aprovado=False)

    # Update the database
    for x in id_list:
      Formulario_denuncia.objects.filter(pk=int(x)).update(aprovado=True)
  
    # Show Success Message and Redirect
    return render(request, 'aprovados.html', {'forms':forms})
  else:
    return render(request, 'engineerFormulario.html', {'forms':forms})
  return render(request, 'engineerFormulario.html', {'forms':forms})

def DescricaoView(request,pk):
  forms = Formulario_denuncia.objects.get(id=pk)
  return render(request, 'formulario_selecionado.html', {'forms':forms})


def DeleteformView(request, pk):
  forms = Formulario_denuncia.objects.get(id=pk)
  if request.method == 'POST':
    forms.delete()
    return redirect('EngenheiroForm')
  return render(request, 'form_del.html', {'forms': forms})


def RiscoView(request):
  encostas = Encosta.objects.all()
  return render(request, 'risco_deslizamento.html', {'encostas': encostas})

class RiscoSearchView(ListView):
  model = Encosta
  template_name = 'risco_deslizamento.html'
  context_object_name = 'encostas'

  def get_queryset(self):
    query = self.request.GET.get('q')
    object_list = Encosta.objects.filter(
      Q(nome__icontains=query) | Q(local__icontains=query) | Q(prioridadeEncosta__icontains=query)
    )

    return object_list

roottsApp/templates/401.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% bootstrap_css %}
    <title>Rootts - Erro</title>
        <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            background-color: #15171B;
        }

        #logo {
            color: #4FDB0D;
            font-size: 1.5rem;
            margin-left: 5rem;
            transition: ease 0.5s;
        }

        #logo:hover {
            font-size: 1.5rem;
            margin-left: 5.5rem;
            transition: ease 0.5s;
            brightness: 1.3;
        }

        .content {
            padding-top: 3rem;
            max-width: 1360px;
            margin: 0 auto;
        }
        p{
            color:white;
        }
        h1{
            color:white;
        }


    </style>
</head>
<body>
    <nav class="navbar navbar-dark" style="padding: 1rem; background-color: #111113; margin-bottom: 1rem;">
        <a class="navbar-brand" href="{% url 'index' %}" id="logo">Rootts</a>
        <ul class="nav" style="margin-right: 5rem">
            <h5 class="text-light">Ola engenheiro(a)</h5>
        </ul>
    </nav>
    <div class="content">
        {% block content %}
        <h1>Error 401</h1>
        <p>Voce nao tem autorizacao para estar aqui!</p>
        {% endblock %}
    </div>
{% bootstrap_javascript jquery='full'%}
</body>
</html>

roottsApp/templates/aprovados.html
{% load humanize %} {% load static %} {% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% bootstrap_css %}
    <title>Document</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      body {
        background-color: #15171b;
        overflow-x: hidden;
      }

      #logo {
        color: #4fdb0d;
        font-size: 1.5rem;
        margin-left: 5rem;
        transition: ease 0.5s;
      }

      #logo:hover {
        font-size: 1.5rem;
        margin-left: 6.5rem;
        transition: ease 0.5s;
      }
      .nav {
        width: 100vw;
        top: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        flex-wrap: nowrap;
        padding: 20px 10px 10px 10px;
      }
      .nav h5 {
        margin-right: 5rem;
      }
      .box-container {
        display: flex;
        flex-wrap: wrap;
        flex-direction: column;
        align-items: flex-start;
        width: 480px;
        padding: 10px 10px 0px 10px;
        height: fit-content;
        margin: 10px 10px 10px 0px;
      }
      .main-content {
        display: flex;
        align-items: center;
        width: 100%;
        justify-content: space-between;
      }
      .main-content h2 {
        font-size: 20px;
      }
      .main-content span {
        font-weight: 400;
      }
      .tudo {
        width: 100vw;
        height: fit-content;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
      }
      .buttons {
        display: flex;
        justify-content: space-between;
        flex-wrap: wrap;
        width: 100%;
      }
      .buttons h4 {
        font-size: 14px;
        margin-top: 10px;
      }
      .head {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 20px;
      }
      .conteudo {
        display: flex;
        width: 85vw;
        align-items: center;
        flex-direction: row;
        justify-content: center;
        flex-wrap: wrap;
      }
      @media (max-width: 900px) {
        #logo {
          margin-left: 0;
        }
        .nav h5 {
          margin-right: 0;
        }
      }
    </style>
  </head>
  <body>
    {% block content %}
    <nav class="nav">
      <a href="{% url 'index' %}" id="logo">
        <img src="{% static "roottsapp/images/roottst.png" %}" alt="rootts"
        id="image" style="width:120px;" />
      </a>
      {% if request.user.is_authenticated %}
        <h5 class="text-light">Olá, {{request.user}}</h5>
      {% endif %}
    </nav>
    <div class="tudo">
      <div class="text-light head">
        <h3 style="font-size: 30px">Reportes Aprovados</h3>
        <a
          href="{% url 'EngenheiroForm' %}"
          class="btn btn-outline-info"
          style="margin: 10px 0px"
          >Pendentes</a
        >
      </div>
      <div class="conteudo">
        {% for form in forms %} {% if form.aprovado %}
        <div class="box-container table-dark">
          <div class="main-content">
            <h2>Nome: <span>{{ form.nome }}</span></h2>
          </div>
          <div class="main-content">
            <h2>Titulo: <span>{{ form.titulo }}</span></h2>
          </div>
          <div class="buttons">
            <div class="box">
              <a
                class="btn-sm btn-warning"
                style="
                  text-decoration: none;
                  padding: 5px;
                  color: white;
                  margin-right: 5px;
                "
                href="{% url 'view_descricao' form.pk %}"
                >Visualizar</a
              >
              <a
                class="btn-sm btn-danger"
                style="text-decoration: none; padding: 5px"
                href="{% url 'del_reporte' form.pk %}"
                >Descartar</a
              >
            </div>
            <h4>{{form.data}}</h4>
          </div>
        </div>
        {% endif %} {% endfor %}
      </div>
    </div>
    {% endblock %}
  </body>
</html>

roottsApp/templates/base.html
{% load bootstrap4 %} {% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/fontawesome.min.css"
      integrity="sha512-RvQxwf+3zJuNwl4e0sZjQeX7kUa3o82bDETpgVCH2RiwYSZVDdFJ7N/woNigN/ldyOOoKw8584jM4plQdt8bhA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
      integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    {% bootstrap_css %}
    <title>Rootts</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      body {
        overflow-x: hidden;
        background-color: #15171b;
      }

      #logo {
        color: #4fdb0d;
        font-size: 1.5rem;
        margin-left: 5rem;
        transition: ease 0.5s;
      }

      #logo:hover {
        font-size: 1.5rem;
        margin-left: 6.5rem;
        transition: ease 0.5s;
      }
      .nav {
        width: 100vw;
        top: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        flex-wrap: nowrap;
        padding: 20px 10px 10px 10px;
      }
      .nav h5 {
        margin-right: 5rem;
      }

      .content {
        padding-top: 3rem;
        width: 100vw;
      }
      .content-table {
        width: 100%;
      }

      .main-content {
        width: 100vw;
        height: 85vh;
        display: flex;
        justify-content: center;
        align-items: center;
      }
      .form {
        width: fit-content;
        background-color: #111113;
        padding: 15px;
      }
      .crud {
        width: 90%;
      }
      .all {
        display: flex;
        width: 100vw;
        height: fit-content;
        justify-content: center;
        align-items: center;
      }
      td {
        padding: 10px 0px 10px 2px;
      }
      .search {
        display: flex;
        justify-content: flex-end;
        width: 95%;
        align-items: center;
        margin-bottom: 20px;
      }
      .search-box {
        display: flex;
        background: none;
        border: 1px solid white;
        border-radius: 5px;
        transition: all 300ms ease-in-out;
      }
      .search-box:focus-within {
        color: #4fdb0d;
        border-color: #4fdb0d;
        transition: all 300ms ease-in-out;
      }
      .search-box:focus-within button {
        color: #4fdb0d;
        transition: all 300ms ease-in-out;
      }
      .search-box input {
        background: none;
        outline: none;
        border: none;
        color: white;
        padding: 5px 8px;
      }
      .search-box button {
        background: none;
        outline: none;
        border: none;
        color: white;
        padding: 5px 8px;
        transition: all 300ms ease-in-out;
      }
      .center {
        margin-bottom: 1rem;
        display: flex;
        align-items: center;
        justify-content: space-between;
        width: 100vw;
        flex-wrap: wrap;
        padding: 10px 0px;
      }
      .add_content {
        width: 100vw;
        height: fit-content;
        margin-top: -50px;
        display: flex;
        justify-content: center;
        align-items: center;
      }
      .add_content form {
        width: 50%;
        padding: 15px;
        box-shadow: 0 0 10px 0px #4fdb0d;
        border: 1px solid #4fdb0d;
        border-radius: 10px;
      }
      @media (max-width: 900px) {
        #logo {
          margin-left: 0;
        }
        .nav h5 {
          margin-right: 0;
        }
        td {
          padding: 2px;
        }
        .buttons {
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          align-items: center;
          {% comment %} height: 70px; {% endcomment %}
        }
        th {
          padding: 5px;
        }
        .center {
          display: flex;
          justify-content: center;
          align-items: center;
        }
        .add_content form {
          width: 100%;
          margin-top: 0;
        }
      }
    </style>
  </head>
  <body>
    <nav class="nav">
      <a href="{% url 'index' %}" id="logo">
        <img src="{% static "roottsapp/images/roottst.png" %}" alt="rootts"
        id="image" style="width:120px;" />
      </a>
      {% if request.user.is_authenticated %}
      <h5 class="text-light">Olá, {{request.user}}</h5>
      {% else %}
      <h5 class="text-light">Olá, usuário(a)</h5>
      {% endif %}
    </nav>
    <div class="content">{% block content %} {% endblock %}</div>
    {% bootstrap_javascript jquery='full'%}
  </body>
</html>

roottsApp/templates/create_variable_encosta.html
<!DOCTYPE html>
{%load static%}
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load bootstrap4 %} {% bootstrap_css %}
    <style>
      * {
        margin: 0;
        padding: 0;
      }
      body {
        background-color: #15171b;
      }

      #logo {
        color: #4fdb0d;
        font-size: 1.5rem;
        margin-left: 5rem;
        transition: ease 0.5s;
      }

      #logo:hover {
        font-size: 1.5rem;
        margin-left: 5.5rem;
        transition: ease 0.5s;
        /* brightness: 1.3; */
      }

      .content {
        padding-top: 3rem;
        max-width: 100vw;
      }
      .main-content {
        width: 100vw;
        height: 80vh;
        display: flex;
        align-items: center;
        justify-content: center;
      }
      .form-box {
        color: white;
        width: 600px;
        height: fit-content;
        background-color: #272727;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        border-radius: 10px;
      }
      .form-box h1 {
        font-size: 23px;
        border-bottom: 1px solid #4fdb0d;
        padding-top: 10px;
      }
      .button-box {
        display: flex;
        align-items: center;
        justify-content: center;
        padding-bottom: 10px;
      }
      .button-box button {
        width: 300px;
        border: 1px solid #3a9b0c;
        font-size: 18px;
        font-weight: 600;
        padding: 5px;
        color: white;
        background: none;
        outline: none;
        border-radius: 5px;
        transition: all 300ms ease-in-out;
      }
      .button-box button:hover {
        background-color: #3a9b0c;
      }
      .content {
        outline: none;
        height: 50px;
        width: 450px;
        background-color: transparent;
        border: 1px solid white;
        color: white;
        padding-left: 5px;
        border-radius: 5px;
      }

      .nome {
        background: none;
        border: 1px solid white;
        padding: 5px;
        color: white;
        outline: none;
        border-radius: 5px;
        width: 250px;
      }
      .form-control {
        width: 250px;
        background-color: transparent;
        border: 1px solid white;
        color: white;
      }
      .form-control:focus-within {
        background-color: transparent;
        outline: none;
        border: none;
      }
      .form-group {
        display: flex;
        flex-direction: column;
      }
      .message-box {
        width: 100vw;
        background-color: red;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 0px;
      }
      .alert {
        width: 500px;
        text-align: center;
        margin-bottom: 0;
      }
    </style>
  </head>
  <body>
    <nav
      class="navbar navbar-dark"
      style="padding: 1rem; background-color: #111113"
    >
      <a class="navbar-brand" href="{% url 'index' %}" id="logo">
        <img src="{% static "roottsapp/images/roottst.png" %}" alt="rootts" id="image" style="width:120px;" />
      </a>
      <ul class="nav" style="margin-right: 5rem">
        <h5 class="text-light">Olá, usuário</h5>
      </ul>
    </nav>
    {% if messages %} {% for message in messages %}
    <div class="message-box">
      <div class="alert {{ message.tags }} alert-dismissible alert-success">
        <a href="{% url 'newVariableView' %}" class="close" data-dismiss="alert">
        </a>
        <strong>{{message}}</strong>
      </div>
    </div>
    {% endfor %} {% endif %}
    <div class="main-content">
      <div class="form-box">
        <h1>Criar Nova Variável</h1>
        <form method="post">
            {% csrf_token %}
            <label for="types" style="padding-top: 10px; padding-bottom: 10px">Data Type:</label>
            <select value="datatype" name="datatype">
            <option value="Integer">Inteiro</option>
            <option value="Float">Float</option>
            <option value="String">String</option>
            </select>

          <div class="form-group">
            <label for="id_nome">Nome:</label>
            <input type="text" name="nome" class="nome" placeholder="Informe o nome da variável">  
          </div>
          
          <div class="form-group">
            <label for="id_content">Conteúdo:</label>
            <input type="text" name="content" class="nome" placeholder="Informe o conteúdo da variável">  
          </div>
          <div class="button-box"">
            <button type="submit" style="padding-bottom: 10px" value="enviar">Confirmar</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

roottsApp/templates/encosta_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% block content %}
<div class="add_content">
    <form action="" method="post" autocomplete="off" class="text-light">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-warning">
                <a style="color:white;text-decoration:none;"href="{% url 'crud' %}">Cancelar</a>
            </button>
        {% endbuttons %}
    </form>  
</div>  

{% endblock %}